config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"#Searchesコントローラーのsearchアクションが実行されるように定義
  #get '/search', to: 'searches#search' でもいける
  #chat機能で追記 get 'chat/:id', to: 'chats#show', as: 'chat' いらんかな
  resources :chats, only: [:show, :create]


  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do#userのネストはフォロワー機能
    resource :relationships, only: [:create, :destroy]
    get 'relationships/followings' => 'relationships#followings', as: 'followings'
    get "relationships/followers" => 'relationships#followers', as: 'followers'
  end

  #resources :groups, except: [:destroy]--exceptは省くやつ
  resources :groups, only: [:new, :index, :show, :create, :edit, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

   # フォローするとき
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  # フォロー外すとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  # フォロー一覧
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  # フォロワー一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_btn.html.erb
<td>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
  <% end %>
</td>

app/views/relationships/_follow_list.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/_follow_num.html.erb
<tr><%= link_to follows_user_path(user) do %>
  <h6>フォロー<%= following_users.count %></h6>
</tr><% end %>&nbsp;&nbsp;
<tr><%= link_to followers_user_path(user) do %>
  <h6>フォロワー<%= follower_users.count %></h6>
</tr><% end %>
<!--これいらんわ-->

app/views/relationships/followers.html.erb
<%= render 'follow_list' %>

app/views/relationships/followings.html.erb
<%= render 'follow_list' %>