config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"#Searchesコントローラーのsearchアクションが実行されるように定義
  #get '/search', to: 'searches#search' でもいける
  #chat機能で追記 get 'chat/:id', to: 'chats#show', as: 'chat' いらんかな
  resources :chats, only: [:show, :create]


  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do#userのネストはフォロワー機能
    resource :relationships, only: [:create, :destroy]
    get 'relationships/followings' => 'relationships#followings', as: 'followings'
    get "relationships/followers" => 'relationships#followers', as: 'followers'
  end

  #resources :groups, except: [:destroy]--exceptは省くやつ
  resources :groups, only: [:new, :index, :show, :create, :edit, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :group_users, dependent: :destroy#グループ化
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy#フォロー機能で追記
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy#フォロー機能で追記

  has_many :followings, through: :relationships, source: :followed#フォロー機能で追記
  has_many :followers, through: :reverse_of_relationships, source: :follower#フォロー機能で追記

  has_many :user_rooms, dependent: :destroy#チャット機能で追記
  has_many :chats, dependent: :destroy#チャット機能で追記
  has_many :rooms, through: :user_rooms#解答で足した

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,length: {maximum:50}


  #プロフ画像初期設定
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  #フォロー,フォロワーの実装
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  #検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")#nameは検索対象であるusersテーブル内のカラム名.適宜、適したカラム名を指定
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

#検索方法分岐-解答パターン
  #def self.search_for(content, method)
    #if method == 'perfect'
      #User.where(name: content)
    #elsif method == 'forward'
      #User.where('name LIKE ?', content + '%')
    #elsif method == 'backward'
      #User.where('name LIKE ?', '%' + content)
    #else
      #User.where('name LIKE ?', '%' + content + '%')
    #end
  #end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books#.page(params[:page]).reverse_orderを課題8bで追記
    @book = Book.new
    @today_book = @books.created_today#応用課題7b
    @yesterday_book = @books.created_yesterday#応用課題7b
    @this_week_book = @books.created_this_week#応用課題7b
    @last_week_book = @books.created_last_week#応用課題7b
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_book_index.html.erb
<h3>投稿数の前日比・前週比</h3>
  <div class = "table_width">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>今日の投稿数</th>
          <th>前日の投稿数</th>
          <th>前日比</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @today_book.count %></td>
          <td><%= @yesterday_book.count %></td>
          <td>
            <% if @yesterday_book.count == 0 %>
              前日の投稿はありません
            <% else %>
              <% @the_day_before =   @today_book.count / @yesterday_book.count.to_f  %>
              <%= (@the_day_before * 100).round %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="table_width">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>今週の投稿数</th>
          <th>前日の投稿数</th>
          <th>前週比</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @this_week_book.count %></td>
          <td><%= @last_week_book.count %></td>
          <% if @last_week_book.count == 0 %>
            <td>先週の投稿はなし</td>
          <% else %>
            <td><% @the_week_before =   @this_week_book.count / @last_week_book.count.to_f  %>
            <%= (@the_week_before * 100).round %>%</td>
          <% end %>
        </tr>
      </tbody>
    </table>

    <table class="table">
     <thead>
        <tr>
          <th>６日前</th>
          <th>5日前</th>
          <th>4日前</th>
          <th>3日前</th>
          <th>２日前</th>
          <th>昨日</th>
          <th>今日</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th><%= @books.created_6days.count %></th>
          <th><%= @books.created_5days.count %></th>
          <th><%= @books.created_4days.count %></th>
          <th><%= @books.created_3days.count %></th>
          <th><%= @books.created_2days.count %></th>
          <th><%= @yesterday_book.count %></th>
          <th><%= @today_book.count %></th>
        </tr>
      </tbody>
    </table>
  </div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if current_user != user%><!--この表記で自分のフォローbtnの表示を消す-->
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% if current_user != user %><!--この表記で自分のフォローbtnの表示を消す-->
    <td><%= render "relationships/follow_btn", user: user %><span><%= link_to 'Begin Chat', chat_path(user.id) %></span></td>
  <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>
<!-- current_userと@userが一致していない場合に`Begin Chat`を表示 -->

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>

  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <div><%=link_to "グループを作成する",new_group_path %> | <%=link_to "グループ一覧",groups_path %></div>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>

  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <%= render 'book_index',books: @books %>
    </div>
  </div>
</div>